language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-1.7.9
  - rbx-2.1.1
matrix:
  allow_failures:
    - rvm: jruby-1.7.9
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsdl1.2-dev
